version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      args:
        LOCAL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - nats-streaming
    links:
      - db
      - nats-streaming
    networks:
      - enrollment

  db:
    container_name: db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - enrollment

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats-streaming
    environment:
      - CLUSTER_ID=test-cluster
      - STORE=nats
      - NATS_SERVER_URL=nats://localhost:4222
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - enrollment

networks:
  enrollment:
    driver: bridge